/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_analisis;
import controller.c_ikan;
import controller.c_kolam;
import controller.c_tahap;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import keeptoo.KButton;
import model.CrudState;
import model.m_analisis;
import model.m_ikan;
import model.m_kolam;
import model.m_tahap;
import model.m_user;
import model.user_session;


public class AnalisisUser extends javax.swing.JFrame implements Observer{

   c_analisis analyzer = new c_analisis();
   c_ikan ikan = new c_ikan();
   c_kolam kolam = new c_kolam();
   c_tahap tahap = new c_tahap();
    public AnalisisUser() {
        initComponents();
        analyzer.addObserver(this);
        setTabelAnalisis(analyzer.getAllAnalisis());
        setIkan(ikan.getAllIkan());
        setKolam(kolam.getAllKolam());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void setTabelAnalisis(List<m_analisis> listAnalisis){
        if (listAnalisis == null) {
            JOptionPane.showMessageDialog(this, "Data Hasil Analisis gagal diambil dari database", "DATABASE FAILED", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                    new String[]{
                        "No",
                        "Id",
                        "Hasil Analisis",
                        "Tanggal Analisis",
                        "Penganalisis",
                        "Nama Kolam",
                        "Nama Ikan"
                    }
            );
            int no = 1;
            for (m_analisis k : listAnalisis) {
                Object[] o = new Object[7];
                o[0] = no;
                o[1] = k.getId();
                o[2] = k.getHasil();
                o[3] = k.getTanggal();
                o[4] = k.getUser().getNama();
                o[5] = k.getKolam().getNamaKolam();
                o[6] = k.getIkan().getNamaIkan();
                tableModel.addRow(o);
                no++;
            }

            tabel_analisis.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tabel_analisis.setModel(tableModel);
            tabel_analisis.getColumnModel().getColumn(0).setMaxWidth(30);
            tabel_analisis.removeColumn(tabel_analisis.getColumnModel().getColumn(1));
            tabel_analisis.getColumnModel().getColumn(2).setMinWidth(100);
            tabel_analisis.getColumnModel().getColumn(3).setMaxWidth(80);
        }
    }
    
    public void setIkan(List<m_ikan> listIkan){
        if(listIkan == null){
            JOptionPane.showMessageDialog(this, "Data Ikan gagal diambil dari database", "DATABASE FAILED", JOptionPane.ERROR_MESSAGE);
        }else{
            jenis_ikan.setModel(new DefaultComboBoxModel(listIkan.toArray()));
        }
    }
    public void setKolam(List<m_kolam> listKolam){
        if(listKolam == null){
            JOptionPane.showMessageDialog(this, "Data Kolam gagal diambil dari database", "DATABASE FAILED", JOptionPane.ERROR_MESSAGE);
        }else{
            pilih_kolam.setModel(new DefaultComboBoxModel(listKolam.toArray()));
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keluar = new keeptoo.KButton();
        menuDashboard = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        analisis = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        pilih_kolam = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jenis_ikan = new javax.swing.JComboBox<>();
        btnAnalisis = new keeptoo.KButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_analisis = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Pengguna");
        setBackground(new java.awt.Color(255, 0, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_logout_rounded_up_16px.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        keluar.setIconTextGap(15);
        keluar.setkEndColor(new java.awt.Color(255, 0, 0));
        keluar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        keluar.setkStartColor(new java.awt.Color(255, 0, 153));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 160, -1));

        menuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_home_16px_4.png"))); // NOI18N
        menuDashboard.setText("Dashboard");
        menuDashboard.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuDashboard.setIconTextGap(15);
        menuDashboard.setkAllowGradient(false);
        menuDashboard.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuDashboard.setkEndColor(new java.awt.Color(255, 51, 255));
        menuDashboard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuDashboard.setkStartColor(new java.awt.Color(255, 51, 0));
        menuDashboard.setMargin(new java.awt.Insets(2, 16, 2, 14));
        menuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SIMAPAN@2x.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        analisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_overtime_16px.png"))); // NOI18N
        analisis.setText("Analisis Ikan");
        analisis.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        analisis.setIconTextGap(15);
        analisis.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        analisis.setkEndColor(new java.awt.Color(255, 51, 255));
        analisis.setkHoverColor(new java.awt.Color(255, 0, 102));
        analisis.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        analisis.setkStartColor(new java.awt.Color(255, 51, 0));
        analisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analisisActionPerformed(evt);
            }
        });
        jPanel1.add(analisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.setkBorderRadius(15);
        kGradientPanel3.setkEndColor(new java.awt.Color(255, 153, 0));
        kGradientPanel3.setkGradientFocus(400);
        kGradientPanel3.setkStartColor(new java.awt.Color(255, 102, 204));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel3.add(pilih_kolam, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jenis Ikan");
        kGradientPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Pilih Kolam");
        kGradientPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jenis_ikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Ikan" }));
        kGradientPanel3.add(jenis_ikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, -1));

        btnAnalisis.setText("Analisis");
        btnAnalisis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisisActionPerformed(evt);
            }
        });
        kGradientPanel3.add(btnAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 110, -1));

        jPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 660, 180));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Analisis Kolam");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        tabel_analisis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabel_analisis);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 660, 280));

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 770, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        masuk masuk = new masuk();
        masuk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void menuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDashboardActionPerformed
        // TODO add your handling code here:
        DashboardUser dashboard = new DashboardUser();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuDashboardActionPerformed

    private void btnAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisisActionPerformed
        // TODO add your handling code here:
        m_ikan ikn = (m_ikan) jenis_ikan.getSelectedItem();
        m_kolam klm = (m_kolam) pilih_kolam.getSelectedItem();
        String hasil = analyzer.hasil_analisis(ikn, klm);
        m_user usr = new m_user(user_session.getId(),user_session.getNama(),user_session.getUsername(),user_session.getLevel(),user_session.getPassword());
        m_analisis an = new m_analisis(null,hasil,null,usr,klm,ikn);
        analyzer.manipulate(an, CrudState.INSERT);
        
    }//GEN-LAST:event_btnAnalisisActionPerformed

    private void analisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analisisActionPerformed
        
        
    }//GEN-LAST:event_analisisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnalisisUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnalisisUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnalisisUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnalisisUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnalisisUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton analisis;
    private keeptoo.KButton btnAnalisis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox<String> jenis_ikan;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KButton keluar;
    private keeptoo.KButton menuDashboard;
    private javax.swing.JComboBox<String> pilih_kolam;
    private javax.swing.JTable tabel_analisis;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
    if (o == analyzer) {
            if (arg == null) {
                JOptionPane.showMessageDialog(this, "Pengguna gagal diperbaharui karena kegagalan koneksi ke database");
            } else {
                m_analisis a = (m_analisis) arg;
                if (analyzer.getCrudState() == CrudState.INSERT) {
                    JOptionPane.showMessageDialog(this, "Hasil Analisis "+ a.getHasil() + " berhasil ditambahkan");
                }
                setTabelAnalisis(analyzer.getAllAnalisis());
            }
        }    
    }
}
