/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_level;
import controller.c_user;
import database.koneksi;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CrudState;
import model.m_level;
import model.m_user;


public class Pengguna extends javax.swing.JFrame implements Observer {

    private String id;
    public String password;

    c_user user = new c_user();
    c_level level = new c_level();

    /**
     * Creates new form Dashboard
     */
    public Pengguna() {
        initComponents();

        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        user.addObserver(this);

        setTabelPengguna(user.getAllUser());
        setLevel(level.getAllLevel());

        if (!koneksi.isConnect()) {
            System.exit(0);
        }

    }

    private void setTabelPengguna(List<m_user> listUser) {
        if (listUser == null) {
            JOptionPane.showMessageDialog(this, "Data Pengguna gagal diambil dari database", "DATABASE FAILED", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                    new String[]{
                        "Id",
                        "Nama Lengkap",
                        "Username",
                        "Id Level",
                        "Level"
                    }
            );
            int no = 1;
            for (m_user u : listUser) {
                Object[] o = new Object[5];
                o[0] = u.getId();
                o[1] = u.getNama();
                o[2] = u.getUsername().toUpperCase();
                o[3] = u.getLevel().getId();
                o[4] = u.getLevel().getLevel();
                tableModel.addRow(o);

            }

            tabel_pengguna.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
            tabel_pengguna.setModel(tableModel);
            tabel_pengguna.getColumnModel().getColumn(0).setMaxWidth(30);
            tabel_pengguna.getColumnModel().getColumn(1).setMinWidth(100);
            tabel_pengguna.getColumnModel().getColumn(2).setMaxWidth(50);
            tabel_pengguna.removeColumn(tabel_pengguna.getColumnModel().getColumn(3));
        }
    }

    public void setLevel(List<m_level> listLevel) {
        if (listLevel == null) {
            JOptionPane.showMessageDialog(this, "Data Level gagal diambil dari database", "DATABASE FAILED", JOptionPane.ERROR_MESSAGE);
        } else {
            level_user.setModel(new DefaultComboBoxModel(listLevel.toArray()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        keluar = new keeptoo.KButton();
        menuDashboard = new keeptoo.KButton();
        menuKolam = new keeptoo.KButton();
        menuIkan = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        menuAnalisis = new keeptoo.KButton();
        menuTahap = new keeptoo.KButton();
        menuPengguna = new keeptoo.KButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_pengguna = new javax.swing.JTable();
        tambah_pengguna = new keeptoo.KButton();
        ubah_pengguna = new keeptoo.KButton();
        Id_field = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        level_user = new javax.swing.JComboBox<>();
        nama_label = new javax.swing.JLabel();
        nama_label1 = new javax.swing.JLabel();
        nama_label2 = new javax.swing.JLabel();
        nama_label3 = new javax.swing.JLabel();
        ubah_password = new javax.swing.JCheckBox();
        nama_lengkap = new javax.swing.JTextField();
        nama_label4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Pengguna");
        setBackground(new java.awt.Color(255, 0, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_logout_rounded_up_16px.png"))); // NOI18N
        keluar.setText("Keluar");
        keluar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        keluar.setIconTextGap(15);
        keluar.setkEndColor(new java.awt.Color(255, 0, 0));
        keluar.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        keluar.setkStartColor(new java.awt.Color(255, 0, 153));
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 160, -1));

        menuDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_home_16px_4.png"))); // NOI18N
        menuDashboard.setText("Dashboard");
        menuDashboard.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuDashboard.setIconTextGap(15);
        menuDashboard.setkAllowGradient(false);
        menuDashboard.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuDashboard.setkEndColor(new java.awt.Color(255, 51, 255));
        menuDashboard.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuDashboard.setkStartColor(new java.awt.Color(255, 51, 0));
        menuDashboard.setMargin(new java.awt.Insets(2, 16, 2, 14));
        menuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(menuDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 160, 40));

        menuKolam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_aquarius_16px_1.png"))); // NOI18N
        menuKolam.setText("Variasi Kolam");
        menuKolam.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuKolam.setIconTextGap(15);
        menuKolam.setkAllowGradient(false);
        menuKolam.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuKolam.setkBorderRadius(15);
        menuKolam.setkEndColor(new java.awt.Color(0, 204, 204));
        menuKolam.setkHoverColor(new java.awt.Color(255, 0, 102));
        menuKolam.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuKolam.setkHoverStartColor(new java.awt.Color(153, 51, 255));
        menuKolam.setkIndicatorThickness(1);
        menuKolam.setkStartColor(new java.awt.Color(204, 255, 0));
        menuKolam.setMargin(new java.awt.Insets(2, 16, 2, 14));
        menuKolam.setOpaque(false);
        menuKolam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKolamActionPerformed(evt);
            }
        });
        jPanel1.add(menuKolam, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 160, -1));

        menuIkan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_fish_16px_1.png"))); // NOI18N
        menuIkan.setText("Jenis Ikan");
        menuIkan.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuIkan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        menuIkan.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        menuIkan.setIconTextGap(15);
        menuIkan.setkAllowGradient(false);
        menuIkan.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuIkan.setkEndColor(new java.awt.Color(0, 204, 204));
        menuIkan.setkHoverColor(new java.awt.Color(255, 0, 102));
        menuIkan.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuIkan.setkStartColor(new java.awt.Color(204, 255, 0));
        menuIkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIkanActionPerformed(evt);
            }
        });
        jPanel1.add(menuIkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SIMAPAN@2x.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 50));

        menuAnalisis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_overtime_16px.png"))); // NOI18N
        menuAnalisis.setText("Analisis Ikan");
        menuAnalisis.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuAnalisis.setIconTextGap(15);
        menuAnalisis.setkAllowGradient(false);
        menuAnalisis.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuAnalisis.setkEndColor(new java.awt.Color(0, 204, 204));
        menuAnalisis.setkHoverColor(new java.awt.Color(255, 0, 102));
        menuAnalisis.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuAnalisis.setkStartColor(new java.awt.Color(204, 255, 0));
        menuAnalisis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAnalisisActionPerformed(evt);
            }
        });
        jPanel1.add(menuAnalisis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 160, -1));

        menuTahap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_honeycombs_filled_16px.png"))); // NOI18N
        menuTahap.setText("Tahap Ikan");
        menuTahap.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuTahap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuTahap.setIconTextGap(15);
        menuTahap.setkAllowGradient(false);
        menuTahap.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuTahap.setkEndColor(new java.awt.Color(0, 204, 204));
        menuTahap.setkHoverColor(new java.awt.Color(255, 0, 102));
        menuTahap.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuTahap.setkStartColor(new java.awt.Color(204, 255, 0));
        menuTahap.setMargin(new java.awt.Insets(2, 16, 2, 14));
        menuTahap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTahapActionPerformed(evt);
            }
        });
        jPanel1.add(menuTahap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 160, -1));

        menuPengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_user_filled_16px.png"))); // NOI18N
        menuPengguna.setText("Pengguna");
        menuPengguna.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        menuPengguna.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuPengguna.setIconTextGap(12);
        menuPengguna.setkBackGroundColor(new java.awt.Color(0, 102, 204));
        menuPengguna.setkEndColor(new java.awt.Color(255, 51, 255));
        menuPengguna.setkHoverColor(new java.awt.Color(255, 0, 102));
        menuPengguna.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        menuPengguna.setkStartColor(new java.awt.Color(255, 51, 0));
        menuPengguna.setMargin(new java.awt.Insets(2, 16, 2, 14));
        menuPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggunaActionPerformed(evt);
            }
        });
        jPanel1.add(menuPengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 160, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Daftar Pengguna");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        tabel_pengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabel_pengguna.setGridColor(new java.awt.Color(51, 153, 255));
        tabel_pengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_penggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_pengguna);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 680, 300));

        tambah_pengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_add_16px.png"))); // NOI18N
        tambah_pengguna.setText("    Tambah Pengguna");
        tambah_pengguna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambah_pengguna.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tambah_pengguna.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tambah_pengguna.setIconTextGap(10);
        tambah_pengguna.setkEndColor(new java.awt.Color(0, 255, 102));
        tambah_pengguna.setkHoverEndColor(new java.awt.Color(0, 204, 51));
        tambah_pengguna.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        tambah_pengguna.setkHoverStartColor(new java.awt.Color(0, 204, 102));
        tambah_pengguna.setkSelectedColor(new java.awt.Color(0, 102, 102));
        tambah_pengguna.setkStartColor(new java.awt.Color(0, 204, 102));
        tambah_pengguna.setMargin(new java.awt.Insets(2, 20, 2, 10));
        tambah_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambah_penggunaActionPerformed(evt);
            }
        });
        jPanel2.add(tambah_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 180, -1));

        ubah_pengguna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_pencil_16px.png"))); // NOI18N
        ubah_pengguna.setText("    Ubah Pengguna");
        ubah_pengguna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ubah_pengguna.setIconTextGap(10);
        ubah_pengguna.setkBackGroundColor(new java.awt.Color(51, 153, 255));
        ubah_pengguna.setkEndColor(new java.awt.Color(51, 153, 255));
        ubah_pengguna.setkHoverEndColor(new java.awt.Color(153, 204, 255));
        ubah_pengguna.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        ubah_pengguna.setkHoverStartColor(new java.awt.Color(0, 153, 204));
        ubah_pengguna.setkSelectedColor(new java.awt.Color(0, 204, 255));
        ubah_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_penggunaActionPerformed(evt);
            }
        });
        jPanel2.add(ubah_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 160, -1));

        Id_field.setToolTipText("Nama Lengkap");
        Id_field.setEnabled(false);
        jPanel2.add(Id_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 60, 30));

        username.setToolTipText("Nama Pengguna");
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 160, 30));

        pass.setText("jPasswordField1");
        pass.setEnabled(false);
        jPanel2.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 130, 30));

        jPanel2.add(level_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 90, 30));

        nama_label.setText("Level Pengguna");
        jPanel2.add(nama_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        nama_label1.setText("ID");
        jPanel2.add(nama_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        nama_label2.setText("Nama Pengguna");
        jPanel2.add(nama_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        nama_label3.setText("Kata Sandi");
        jPanel2.add(nama_label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        ubah_password.setText("Ubah Password");
        ubah_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_passwordActionPerformed(evt);
            }
        });
        jPanel2.add(ubah_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        nama_lengkap.setToolTipText("Nama Lengkap");
        jPanel2.add(nama_lengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 180, 30));

        nama_label4.setText("Nama Lengkap");
        jPanel2.add(nama_label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 770, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        masuk masuk = new masuk();
        masuk.setVisible(true);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void menuKolamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKolamActionPerformed
        // TODO add your handling code here:
        Kolam kolam = new Kolam();
        kolam.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuKolamActionPerformed

    private void menuIkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIkanActionPerformed
        // TODO add your handling code here:
        Ikan ikan = new Ikan();
        ikan.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuIkanActionPerformed

    private void menuAnalisisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAnalisisActionPerformed
        // TODO add your handling code here:
        Analisis analisis = new Analisis();
        analisis.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuAnalisisActionPerformed

    private void menuPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuPenggunaActionPerformed

    private void menuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDashboardActionPerformed
        // TODO add your handling code here:
        Pembenihan dashboard = new Pembenihan();
        dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuDashboardActionPerformed

    private void menuTahapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTahapActionPerformed
        // TODO add your handling code here:
        Tahap tahap = new Tahap();
        tahap.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuTahapActionPerformed

    private void tambah_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambah_penggunaActionPerformed
        // TODO add your handling code here:
        String id_user = null;
        String nama_peng = username.getText();
        String nama = nama_lengkap.getText();
        String pwd = pass.getText();
        m_level lvl = (m_level) level_user.getSelectedItem();
        m_user u = new m_user(id_user, nama_peng, nama, lvl, pwd);        
        user.manipulate(u,CrudState.INSERT);

    }//GEN-LAST:event_tambah_penggunaActionPerformed

    private void ubah_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_penggunaActionPerformed
        tambah_pengguna.setEnabled(true);
        ubah_pengguna.setSelected(false);
        String id_user = Id_field.getText();
        String nama_peng = username.getText();
        String nama = nama_lengkap.getText();
        String pwd = pass.getText();
        m_level lvl = (m_level) level_user.getSelectedItem();
        m_user u = new m_user(id_user, nama_peng, nama, lvl, pwd);        
        user.manipulate(u,CrudState.UPDATE);
        
    }//GEN-LAST:event_ubah_penggunaActionPerformed

    private void tabel_penggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_penggunaMouseClicked
        tambah_pengguna.setEnabled(false);
        tambah_pengguna.setSelected(true);
        int baris = tabel_pengguna.rowAtPoint(evt.getPoint());
        List<m_user> listUser = user.getUserByID(tabel_pengguna.getModel().getValueAt(baris, 0).toString());
        for (m_user u : listUser) {
            Id_field.setText(u.getId());
            nama_lengkap.setText(u.getNama());
            username.setText(u.getUsername());
            pass.setText(u.getPassword());
            level_user.getModel().setSelectedItem(u.getLevel().getLevel());
            username.setEnabled(false);
            
        }


    }//GEN-LAST:event_tabel_penggunaMouseClicked

    private void ubah_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_passwordActionPerformed
        // TODO add your handling code here:
        if(ubah_password.isSelected()){
          pass.setEnabled(true);  
        }else{
          pass.setEnabled(false);
        }
        
    }//GEN-LAST:event_ubah_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private keeptoo.KButton keluar;
    private javax.swing.JComboBox<String> level_user;
    private keeptoo.KButton menuAnalisis;
    private keeptoo.KButton menuDashboard;
    private keeptoo.KButton menuIkan;
    private keeptoo.KButton menuKolam;
    private keeptoo.KButton menuPengguna;
    private keeptoo.KButton menuTahap;
    private javax.swing.JLabel nama_label;
    private javax.swing.JLabel nama_label1;
    private javax.swing.JLabel nama_label2;
    private javax.swing.JLabel nama_label3;
    private javax.swing.JLabel nama_label4;
    private javax.swing.JTextField nama_lengkap;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTable tabel_pengguna;
    private keeptoo.KButton tambah_pengguna;
    private javax.swing.JCheckBox ubah_password;
    private keeptoo.KButton ubah_pengguna;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o == user) {
            if (arg == null) {
                JOptionPane.showMessageDialog(this, "Pengguna gagal diperbaharui karena kegagalan koneksi ke database");
            } else {
                m_user u = (m_user) arg;
                if (user.getCrudState() == CrudState.INSERT) {
                    JOptionPane.showMessageDialog(this, u.getNama() + " berhasil ditambahkan");
                }else if (user.getCrudState() == CrudState.UPDATE){
                    JOptionPane.showMessageDialog(this, u.getNama() + " berhasil diperbarui");
                }
                setTabelPengguna(user.getAllUser());
            }
        }
    }
}
